- name: Restart LDAP Service
  service:
    name: slapd
    state: restarted
    enabled: yes

- name: Run Bash script and capture NEW_CONFIG_PASSWD
  shell: |
    slappasswd -h {SSHA} -s {{ CNCONFIGADMINPASSWD }}
  register: new_config_passwd_output
    
- name: Set NEW_CONFIG_PASSWD Ansible variable
  set_fact:
    NEW_CONFIG_PASSWD: "{{ new_config_passwd_output.stdout }}"

- name: Run Bash script and capture NEW_ADMIN_PASSWD
  shell: |
    slappasswd -h {SSHA} -s {{ ADMINPASSWD }}
  register: new_admin_passwd_output
    
- name: Set NEW_ADMIN_PASSWD Ansible variable
  set_fact:
    NEW_ADMIN_PASSWD: "{{ new_admin_passwd_output.stdout }}"
