---
mysql_port: 3306

json_data:
  liderLocale: "tr"
  ldapServer: "192.168.56.135"
  ldapPort: "389"
  ldapUsername: "cn=admin,dc=liderahenk,dc=org"
  ldapPassword: "1"
  ldapRootDn: "dc=liderahenk,dc=org"
  ldapUseSsl: "false"
  ldapSearchAttributes: "cn,objectClass,uid,liderPrivilege"
  ldapAllowSelfSignedCert: "false"
  ldapMailNotifierAttributes: "cn, mail, departmentNumber, uid"
  ldapEmailAttribute: "mail"
  agentLdapBaseDn: "ou=Agents,dc=liderahenk,dc=org"
  agentLdapIdAttribute: "cn"
  agentLdapJidAttribute: "uid"
  agentLdapObjectClasses: "pardusDevice,device"
  userLdapBaseDn: "ou=Users,dc=liderahenk,dc=org"
  userLdapUidAttribute: "uid"
  userLdapPrivilegeAttribute: "liderPrivilege"
  userLdapObjectClasses: "pardusAccount,pardusLider"
  userAuthorizationEnabled: "true"
  groupLdapObjectClasses: "groupOfNames"
  roleLdapObjectClasses: "sudoRole"
  userLdapRolesDn: "ou=Role,ou=Groups,dc=liderahenk,dc=org"
  groupLdapBaseDn: "ou=Groups,dc=liderahenk,dc=org"
  userGroupLdapBaseDn: "ou=User,ou=Groups,dc=liderahenk,dc=org"
  ahenkGroupLdapBaseDn: "ou=Agent,ou=Groups,dc=liderahenk,dc=org"
  xmppHost: "192.168.56.135"
  xmppPort: "5222"
  xmppUsername: "lider_sunucu"
  xmppPassword: "1"
  xmppResource: "Smack"
  xmppServiceName: "im.liderahenk.org"
  xmppMaxRetryConnectionCount: "7"
  xmppPacketReplayTimeout: "10000"
  xmppPingTimeout: "300"
  xmppUseSsl: "false"
  xmppAllowSelfSignedCert: "false"
  xmppUseCustomSsl: "false"
  xmppPresencePriority: "1"
  xmppBoshAddress: "http://192.168.56.135:5280/bosh"
  fileServerProtocol: "SSH"
  fileServerHost: "192.168.56.135"
  fileServerUsername: "pardus"
  fileServerPassword: "123123qwe"
  fileServerPluginPath: "/home/pardus/plugins/ahenk-{0}_{1}_amd64.deb"
  fileServerAgreementPath: "/home/pardus/sample-agreement.txt"
  fileServerAgentFilePath: "/home/pardus/agent-files/{0}/"
  fileServerUrl: "null"
  fileServerPort: "22"
  taskManagerCheckFutureTask: "null"
  taskManagerFutureTaskCheckPeriod: "null"
  alarmCheckReport: "null"
  mailAddress: "liderahenk.mys@gmail.com"
  mailPassword: "rKSyBHa29fE6S"
  mailHost: "smtp.gmail.com"
  mailSmtpPort: "587"
  mailSmtpAuth: "true"
  mailSmtpStartTlsEnable: "true"
  mailSmtpSslEnable: "null"
  mailSmtpConnTimeout: "null"
  mailSmtpTimeout: "null"
  mailSmtpWriteTimeout: "null"
  mailSendOnTaskCompletion: "null"
  mailCheckTaskCompletionPeriod: "null"
  mailSendOnPolicyCompletion: "null"
  mailCheckPolicyCompletionPeriod: "null"
  hotDeploymentPath: "null"
  cronTaskList: "null"
  entrySizeLimit: "null"
  cronIntervalEntrySize: "null"
  adDomainName: "lawad.local"
  adHostName: "lawad.lawad.local"
  adIpAddress: "161.9.194.156"
  adAdminUserName: "Administrator"
  adAdminUserFullDN: "cn=Administrator,cn=Users,dc=lawad,dc=local"
  adAdminPassword: "Passw0rd"
  adPort: "389"
  adUseSSL: "false"
  adUseTLS: "true"
  adAllowSelfSignedCert: "true"
  allowDynamicDNSUpdate: "true"
  disableLocalUser: "false"
  domainType: "LDAP"
  sudoRoleType: "LDAP"
  ahenkRepoAddress: "null"
  ahenkRepoKeyAddress: "null"
  allowVNCConnectionWithoutPermission: "true"
  pardusRepoAddress: "http://depo.pardus.org.tr/pardus"
  pardusRepoComponent: "yirmibir main contrib non-free"
  enableDelete4Directory: "null"
  selectedRegistrationType: "HOSTNAME"