- name: ldap için bu
  hosts: [ldap_server]
  become: yes
  roles:
    - mariadb
  vars_files:
    - /home/test/liderahenk-ansible/roles/mariadb/vars/main.yml

- name: ldap için bu
  hosts: [ldap_server]
  become: yes
  roles:
    - ldap_remake
  vars_files:
    - /home/test/liderahenk-ansible/roles/ldap_remake/vars/main.yml

- name: ldap için bu
  hosts: [ldap_server]
  become: yes
  roles:
    - xmpp
  vars_files:
    - /home/test/liderahenk-ansible/roles/xmpp/vars/main.yml

  