- name: mariaDB için bu
  hosts: [db_server]
  # vars:
  #   ansible_ssh_user: test
  #   ansible_become: true
  #   ansible_become_pass: 1
  become: yes
  roles:
    - mariadb

# - name: TEST için
#   hosts: [file_server]
#   # vars:
#   #   ansible_ssh_user: test
#   #   ansible_become: true
#   #   ansible_become_pass: 1
#   become: yes
#   roles:
#     - test01

  # tasks:
  #   - name: Ping my hosts
  #     ansible.builtin.ping:
  #   - name: Print message
  #     ansible.builtin.debug:
  #       msg: Ping is OK
  #   - name: Install htop  (state=present is optional)
  #     ansible.builtin.apt:
  #       name: mariadb-server
  #       state: present
  #   - name: Print message
  #     ansible.builtin.debug:
  #       msg: htop is installed
